### PR TITLE
fix\!: remove default active pin for autotasks

### LINKED ISSUE #120: Remove default config of AutomatedTabTask
For now, all tasks without a default configuration will update its target tab to `pinned`.  The only way to avoid this is to come with a `pinned: false`. However, it will update its target tab to be `not pinned`. I think the default value should be `undefined` to leave the original pinned state to be untouched.

Maybe the same applies to other options too.

### PR DESCRIPTION
**Pull request by Jack-Works**
close #120 @SunriseFox is it ok?

### CODE REVIEW

File: src/Extension/AutomatedTabTask.ts [hunk 1]
```diff
@@ -300,15 +298,20 @@ async function getTabOrCreate(
...
+    active: boolean | undefined,
+    pinned: boolean | undefined,
 ) {
+    const finalOpts = { active, pinned, url }
+    // Gecko view doesn't support this.
+    if (finalOpts.pinned === undefined) delete finalOpts.pinned
+    if (finalOpts.active === undefined) delete finalOpts.active
     if (typeof openInCurrentTab === 'number') {
-        await browser.tabs.update(openInCurrentTab, { url: needRedirect ? url : undefined, active, pinned })
+        if (needRedirect) delete finalOpts.url
```
Comment (SunriseFox) [inline src/Extension/AutomatedTabTask.ts]: should be `!needRedirect`...?

File: src/Extension/AutomatedTabTask.ts [hunk 2]
```diff
@@ -37,7 +37,7 @@ export interface AutomatedTabTaskSharedOptions {
      * Should the new tab to be active?
      * @defaultValue false
```
Comment (SunriseFox) [inline src/Extension/AutomatedTabTask.ts]: should docs like this be updated?

File: src/Extension/AutomatedTabTask.ts (hunk 1 above)
Comment (Jack-Works) [reply src/Extension/AutomatedTabTask.ts]: ah you re right
